
Couldn't find processed data. Processing...
Epsilon: 0.15
Example No: 0 Label: 32
Traceback (most recent call last):
  File "/home/ayberk/PycharmProjects/FederatedFP/venv/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/ayberk/PycharmProjects/FederatedFP/venv/lib/python3.9/site-packages/tensorflow/python/eager/execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnimplementedError: Exception encountered when calling layer "conv2d" (type Conv2D).
DNN library is not found. [Op:Conv2D]
Call arguments received by layer "conv2d" (type Conv2D):
